from Products.FacultyStaffDirectory.extenderInstallation import installExtenderGloballyIfLocallyIsNotSupported

from Products.sleicPersonExtender.person import addSleicFields
from Products.sleicPersonExtender.person import modifySleicFields

installExtenderGloballyIfLocallyIsNotSupported(addSleicFields, 'sleicPersonExtender')
installExtenderGloballyIfLocallyIsNotSupported(modifySleicFields, 'sleicPersonExtender')
